variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PKG_VER: 0.0.0

#linux:
#  stage: build
#  tags: [linux]
#  script: cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
#  artifacts:
#    name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
#    paths: [$CI_PROJECT_TITLE]

ubuntu:
    stage: build
    tags: [ubuntu]
    script:
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
        - mkdir -p deb/DEBIAN
        - "echo 'Package: DiagnosticAgent' > deb/DEBIAN/control"
        - "echo 'Version: '$PKG_VER >> deb/DEBIAN/control"
        - "echo 'Architecture: amd64' >> deb/DEBIAN/control"
        #- "echo 'Depends: libqwt-qt5-6_6.1.2-6_amd64.deb' >> deb/DEBIAN/control"

        - "echo '#!/bin/bash' > deb/DEBIAN/postinst"
        - "echo 'chmod ugo+rw /opt/DiagnosticAgent -R' > deb/DEBIAN/postinst"
        - chmod +x deb/DEBIAN/postinst
        - mkdir -p deb/opt/DiagnosticAgent/bin
        - cp DiagnosticAgent deb/opt/DiagnosticAgent
        - cp resources/config.json deb/opt/DiagnosticAgent
    artifacts:
        name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
        paths: [$CI_PROJECT_TITLE, DiagnosticAgent_$CI_COMMIT_REF_NAME.deb]

astra1.6:
    stage: build
    tags: [astra1.6]
    script:
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
        - mkdir -p deb/DEBIAN
        - "echo 'Package: DiagnosticAgent' > deb/DEBIAN/control"
        - "echo 'Version: '$PKG_VER >> deb/DEBIAN/control"
        - "echo 'Architecture: amd64' >> deb/DEBIAN/control"
        #- "echo 'Depends: libqwt-qt5-6' >> deb/DEBIAN/control"

        - "echo '#!/bin/bash' > deb/DEBIAN/postinst"
        - "echo 'chmod ugo+rw /opt/DiagnosticAgent -R' > deb/DEBIAN/postinst"
        - chmod +x deb/DEBIAN/postinst
        - mkdir -p deb/opt/DiagnosticAgent
        - cp DiagnosticAgent deb/opt/DiagnosticAgent
    artifacts:
        name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
        paths: [$CI_PROJECT_TITLE, DiagnosticAgent_$CI_COMMIT_REF_NAME.deb]


windows:
  stage: build
  tags: [windows]
  script:
    - mingw64-cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
    - mkdir $CI_PROJECT_TITLE && cp $CI_PROJECT_TITLE.exe $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/iconv.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libgcc_s_seh-1.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libpcre2-16-0.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libssp-0.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libstdc++-6.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libwinpthread-1.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/Qt5Core.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/zlib1.dll $CI_PROJECT_TITLE
  artifacts:
    name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
    paths: [$CI_PROJECT_TITLE]
