variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0

alse:
  stage: build
  tags: [alse]
  script:
    - cmake . && make && strip $CI_PROJECT_TITLE
    - mkdir -p deb/DEBIAN
    - GIT_VERSION=$(git describe --tags --always)
    - "echo 'Package: '$CI_PROJECT_TITLE > deb/DEBIAN/control"
    - "echo 'Version: '1.0 >> deb/DEBIAN/control"
    - "echo 'Architecture: amd64' >> deb/DEBIAN/control"
    - mkdir -p deb/opt/$CI_PROJECT_TITLE
    - cp $CI_PROJECT_TITLE deb/opt/$CI_PROJECT_TITLE
    - mkdir -p deb/lib/x86_64-linux-gnu
    - cp libs/LPVL/liblpvl.so deb/lib/x86_64-linux-gnu
    - cp libs/CCL/libccl.so deb/lib/x86_64-linux-gnu
    - mkdir -p deb/usr/share/applications
    - cp $CI_PROJECT_TITLE.desktop deb/usr/share/applications
    - dpkg-deb -b deb $CI_PROJECT_TITLE'_'$GIT_VERSION'_'amd64.deb
  artifacts:
    name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_TIMESTAMP-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    paths: [$CI_PROJECT_TITLE, ./*.deb]

windows:
  stage: build
  tags: [windows]
  script:
     - mingw64-cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
     - mkdir -p $CI_PROJECT_TITLE/plugins $CI_PROJECT_TITLE/qml
     - mkdir -p $CI_PROJECT_TITLE/plugins/geoservices $CI_PROJECT_TITLE/plugins/bearer $CI_PROJECT_TITLE/plugins/iconengines 
     - mkdir -p $CI_PROJECT_TITLE/plugins/platforms $CI_PROJECT_TITLE/plugins/imageformats
     - cp QuaSAR.exe $CI_PROJECT_TITLE
     - cp libs/LPVL/liblpvl.dll $CI_PROJECT_TITLE
     - cp libs/CCL/libccl.dll $CI_PROJECT_TITLE

     - cpwinlib libgcc_s_seh-1.dll $CI_PROJECT_TITLE
     - cpwinlib libEGL.dll $CI_PROJECT_TITLE
     - cpwinlib libGLESv2.dll $CI_PROJECT_TITLE
     - cpwinlib libstdc++-6.dll $CI_PROJECT_TITLE
     - cpwinlib libwinpthread-1.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Core.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Gui.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Location.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Network.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Positioning.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5PositioningQuick.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Qml.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5QmlModels.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5QmlWorkerScript.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Quick.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5QuickControls2.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5QuickTemplates2.dll $CI_PROJECT_TITLE
     - cpwinlib Qt5Svg.dll $CI_PROJECT_TITLE  
     - cpwinlib Qt5Widgets.dll $CI_PROJECT_TITLE # too bad i have to include this just 4 qml file dialog. maybe i will replace it with custom version.

     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/geoservices/qtgeoservices_osm.dll $CI_PROJECT_TITLE/plugins/geoservices
     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/imageformats/qjpeg.dll $CI_PROJECT_TITLE/plugins/imageformats
     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/imageformats/qsvg.dll $CI_PROJECT_TITLE/plugins/imageformats
     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/imageformats/qgif.dll $CI_PROJECT_TITLE/plugins/imageformats
     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/platforms/qwindows.dll $CI_PROJECT_TITLE/plugins/platforms
     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/bearer/qgenericbearer.dll $CI_PROJECT_TITLE/plugins/bearer
     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/iconengines/qsvgicon.dll $CI_PROJECT_TITLE/plugins/iconengines

     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/Qt $CI_PROJECT_TITLE/qml
     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtGraphicalEffects $CI_PROJECT_TITLE/qml
     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtLocation $CI_PROJECT_TITLE/qml
     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtPositioning $CI_PROJECT_TITLE/qml
     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtQml $CI_PROJECT_TITLE/qml
     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtQuick $CI_PROJECT_TITLE/qml
     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtQuick.2 $CI_PROJECT_TITLE/qml

  artifacts:
    name: $CI_PROJECT_TITLE-$CI_COMMIT_TAG-$CI_COMMIT_REF_NAME
    paths: [$CI_PROJECT_TITLE]
    expire_in: 1 day
