variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PKG_VER: 0.0.0

ubuntu:
    stage: build
    tags: [ubuntu]
    script:
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
        - mkdir -p deb/DEBIAN
        - "echo 'Package: DiagnosticAgent' > deb/DEBIAN/control"
        - "echo 'Version: '$PKG_VER >> deb/DEBIAN/control"
        - "echo 'Architecture: amd64' >> deb/DEBIAN/control"
        #- "echo 'Depends: libqwt-qt5-6_6.1.2-6_amd64.deb' >> deb/DEBIAN/control"

        - "echo '#!/bin/bash' > deb/DEBIAN/postinst"
        - "echo 'chmod ugo+rw /opt/DiagnosticAgent -R' > deb/DEBIAN/postinst"
        - chmod +x deb/DEBIAN/postinst
    artifacts:
        name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
        paths: [$CI_PROJECT_TITLE, DiagnosticAgent_$CI_COMMIT_REF_NAME.deb]

astra1.6:
    stage: build
    tags: [astra1.6]
    script:
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
        - mkdir -p deb/DEBIAN
        - "echo 'Package: DiagnosticAgent' > deb/DEBIAN/control"
        - "echo 'Version: '$PKG_VER >> deb/DEBIAN/control"
        - "echo 'Architecture: amd64' >> deb/DEBIAN/control"
        #- "echo 'Depends: libqwt-qt5-6' >> deb/DEBIAN/control"

        - "echo '#!/bin/bash' > deb/DEBIAN/postinst"
        - "echo 'chmod ugo+rw /opt/DiagnosticAgent -R' > deb/DEBIAN/postinst"
        - chmod +x deb/DEBIAN/postinst
    artifacts:
        name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
        paths: [$CI_PROJECT_TITLE, DiagnosticAgent_$CI_COMMIT_REF_NAME.deb]

windows:
  stage: build
  tags: [windows]
  script:
    - mingw64-cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_SHARED_LINKER_FLAGS="-static -static-libgcc" && cmake --build .
    - mkdir -p $CI_PROJECT_TITLE/geoservices $CI_PROJECT_TITLE/imageformats $CI_PROJECT_TITLE/platforms
    - cp Quasar.exe $CI_PROJECT_TITLE
    - cp libplugin/plugin.dll $CI_PROJECT_TITLE
    - cpwinlib iconv.dll $CI_PROJECT_TITLE
    - cpwinlib libbz2-1.dll $CI_PROJECT_TITLE
    - cpwinlib libcfitsio-3.dll $CI_PROJECT_TITLE
    - cpwinlib libcharset-1.dll $CI_PROJECT_TITLE
    - cpwinlib libcrypto-1_1-x64.dll $CI_PROJECT_TITLE
    - cpwinlib libcurl-4.dll $CI_PROJECT_TITLE
    - cpwinlib libexpat-1.dll $CI_PROJECT_TITLE
    - cpwinlib libfreetype-6.dll $CI_PROJECT_TITLE
    - cpwinlib libfreexl-1.dll $CI_PROJECT_TITLE
    - cpwinlib libgcc_s_seh-1.dll $CI_PROJECT_TITLE
    - cpwinlib libgdal-29.dll $CI_PROJECT_TITLE
    - cpwinlib libgeos-3.9.2.dll $CI_PROJECT_TITLE
    - cpwinlib libgeos_c-1.dll $CI_PROJECT_TITLE
    - cpwinlib libgeotiff-5.dll $CI_PROJECT_TITLE
    - cpwinlib libgif-7.dll $CI_PROJECT_TITLE
    - cpwinlib libglib-2.0-0.dll $CI_PROJECT_TITLE
    - cpwinlib libgta-1.dll $CI_PROJECT_TITLE
    - cpwinlib libharfbuzz-0.dll $CI_PROJECT_TITLE
    - cpwinlib libidn2-0.dll $CI_PROJECT_TITLE
    - cpwinlib libintl-8.dll $CI_PROJECT_TITLE
    - cpwinlib libjasper-4.dll $CI_PROJECT_TITLE
    - cpwinlib libjpeg-62.dll $CI_PROJECT_TITLE
    - cpwinlib libkmlbase.dll $CI_PROJECT_TITLE
    - cpwinlib libkmldom.dll $CI_PROJECT_TITLE
    - cpwinlib libkmlengine.dll $CI_PROJECT_TITLE
    - cpwinlib liblzma-5.dll $CI_PROJECT_TITLE
    - cpwinlib libminizip-3.0.dll $CI_PROJECT_TITLE
    - cpwinlib libopenjp2.dll $CI_PROJECT_TITLE
    - cpwinlib libpcre-1.dll $CI_PROJECT_TITLE
    - cpwinlib libpcre2-16-0.dll $CI_PROJECT_TITLE
    - cpwinlib libpng16-16.dll $CI_PROJECT_TITLE
    - cpwinlib libpq.dll $CI_PROJECT_TITLE
    - cpwinlib libproj_8_2.dll $CI_PROJECT_TITLE
    - cpwinlib librttopo-1.dll $CI_PROJECT_TITLE
    - cpwinlib libspatialite-4.dll $CI_PROJECT_TITLE
    - cpwinlib libsqlite3-0.dll $CI_PROJECT_TITLE
    - cpwinlib libssh2-1.dll $CI_PROJECT_TITLE
    - cpwinlib libssl-1_1-x64.dll $CI_PROJECT_TITLE
    - cpwinlib libssp-0.dll $CI_PROJECT_TITLE
    - cpwinlib libstdc++-6.dll $CI_PROJECT_TITLE
    - cpwinlib libtiff-5.dll $CI_PROJECT_TITLE
    - cpwinlib liburiparser-1.dll $CI_PROJECT_TITLE
    - cpwinlib libwebp-7.dll $CI_PROJECT_TITLE
    - cpwinlib libwinpthread-1.dll $CI_PROJECT_TITLE
    - cpwinlib libxml2-2.dll $CI_PROJECT_TITLE
    - cpwinlib libzstd.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Charts.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Core.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Gui.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Location.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Multimedia.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5MultimediaQuick.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Network.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5OpenGL.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Positioning.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5PositioningQuick.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Qml.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5QmlModels.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5QmlWorkerScript.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Quick.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5QuickControls2.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5QuickShapes.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5QuickTemplates2.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5QuickWidgets.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Svg.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5Widgets.dll $CI_PROJECT_TITLE
    - cpwinlib Qt5WinExtras.dll $CI_PROJECT_TITLE
    - cpwinlib qwt-qt5.dll $CI_PROJECT_TITLE
    - cpwinlib SDL2.dll $CI_PROJECT_TITLE
    - cpwinlib zlib1.dll $CI_PROJECT_TITLE
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/geoservices/qtgeoservices_osm.dll $CI_PROJECT_TITLE/geoservices
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/imageformats/qjpeg.dll $CI_PROJECT_TITLE/imageformats
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/imageformats/qsvg.dll $CI_PROJECT_TITLE/imageformats
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/plugins/platforms/qwindows.dll $CI_PROJECT_TITLE/platforms
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/Qt $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtCharts $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtGraphicalEffects $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtLocation $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtMultimedia $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtPositioning $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtQml $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtQuick $CI_PROJECT_TITLE
    - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5/qml/QtQuick.2 $CI_PROJECT_TITLE
 #   - cp -r settings $CI_PROJECT_TITLE
  artifacts:
    name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TIMESTAMP
    paths: [$CI_PROJECT_TITLE]
